# Generated by Django 5.0 on 2023-12-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_is_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
