# Generated by Django 5.0 on 2023-12-21 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_is_editor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_editor',
            field=models.BooleanField(default=False),
        ),
    ]
