# Generated by Django 5.0 on 2023-12-22 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_is_editor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_editor',
        ),
    ]
